version: '3.8'
services:
    next-web:
        image: nginx:latest
        container_name: nginx
        ports:
            - 127.0.0.1:80:80
        tty: true
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
    next-ap:
        build: .
        container_name: next
        ports:
            - 127.0.0.1:3000:3000
        tty: true
        volumes:
            - ./source:/var/www/html
            - /var/www/html/next-app/node_modules
    next-db:
        image: postgres:latest
        container_name: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=next-db
        ports:
            - 127.0.0.1:5433:5432
volumes:
    postgres-data:
